ANTURINIMI = 'dht22-sensorname'
VALOANTURINIMI = 'kanalaulko-valoanturi'
ANTURIVALONOHJAUS = 'kanalasisa-valonohjaus'
MQTTKAYTTAJA = 'useri'
MQTTSALARI = 'salari'
MQTTSERVERI = 'localhost'
MQTTSERVERIPORTTI = 1883
AIHELAMPO = 'kanala/sisa/lampo'
AIHEKOSTEUS = 'kanala/sisa/kosteus'
AIHEVALOISUUS = 'kanala/ulko/valoisuus'
AIHEINFRAPUNA = 'kanala/ulko/infrapuna'
AIHEUV = 'kanala/ulko/uv'
DHT22PINNI = 4
LUKUVALI = 60
RELE1_PINNI = 6
RELE2_PINNI = 13
RELE3_PINNI = 19
RELE4_PINNI = 26
RELE1_MQTTAIHE_1 = 'kanala/sisa/valaistus'  # aihe josta valon status luetaan
RELE2_MQTTAIHE_2 = 'kanala/sisa/lammitys'  # aihe josta lammityksen status luetaan
RELE3_MQTTAIHE_3 = 'kanala/ulko/valaistus'  # aihe josta ulkovalon status luetaan
RELE4_MQTTAIHE_4 = 'kanala/ulko/halytys'  # aihe josta halytys status luetaan
REEDANTURI = 'kanalaulko-reedanturi'
REEDPINNI = 36  # gpio-numero
REEDAIHE = 'kanala/ulko/luukkukytkin'
LUUKKUAIHE = 'kanala/ulko/luukku'
LUUKKUANTURI = 'luukku-433mhz-broker'
LUUKKUAURINKOMQTT = 'luukku-auringon-lasku'
SISAVALO_PAALLE = '08:00'
SISAVALO_POIS = '21:00'
LONGITUDI = 22.937540   # auringon laskemisaikaan tarvittavat tiedot
LATITUDI = 59.836250 # auringon laskemisaikaan tarvittavat tiedot
ULKOLUUKKU_KIINNI_VIIVE = 60  # auringon laskust aminuutteina
