''' Esimerkki parametrit.py-tiedostosta
MQTTKAYTTAJA = 'useri'
MQTTSALARI = 'salari'
MQTTSERVERI = 'localhost'
MQTTSERVERIPORTTI = 1883
AIHE_MH_ETELA_LAMPO = 'koti/sisa/mhetela/lampo'
AIHE_MH_ETELA_KOSTEUS = 'koti/sisa/mhetela/kosteus'
AIHE_MH_LANSI_LAMPO = 'koti/sisa/mhlansi/lampo'
AIHE_MH_LANSI_KOSTEUS = 'koti/sisa/mhlansi/kosteus'
AIHE_MH_POHJOINEN_LAMPO = 'koti/sisa/mhpohjoinen/lampo'
AIHE_MH_POHJOINEN_KOSTEUS = 'koti/sisa/mhpohjoinen/kosteus'
AIHE_MH_ITA_LAMPO = 'koti/sisa/mhita/lampo'
AIHE_MH_ITA_KOSTEUS = 'koti/sisa/mhita/kosteus'
AIHE_OLOHUONE_LAMPO = 'koti/sisa/olohuone/lampo'
AIHE_OLOHUONE_KOSTEUS = 'koti/sisa/olohuone/kosteus'
AIHE_TAKKAHUONE_LAMPO = 'koti/sisa/takkahuone/lampo'
AIHE_TAKKAHUONE_KOSTEUS = 'koti/sisa/takkahuone/kosteus'
AIHE_PESUHUONE_LAMPO = 'koti/sisa/pesuhuone/lampo'
AIHE_PESUHUONE_KOSTEUS = 'koti/sisa/pesuhuone/kosteus'
AIHE_VARASTO_POHJOINEN_LAMPO = 'koti/sisa/varastopohjoinen/lampo'
AIHE_VARASTO_POHJOINEN_KOSTEUS = 'koti/sisa/varastopohjoinen/kosteus'
AIHE_AUTOTALLI_LAMPO = 'koti/sisa/autotalli/lampo'
AIHE_AUTOTALLI_KOSTEUS = 'koti/sisa/autotalli/kosteus'
AIHE_ULLAKKO_LAMPO = 'koti/ulko/ullakko/lampo'
AIHE_ULLAKKO_KOSTEUS = 'koti/ulko/ullakko/kosteus'
VARASTO_POHJOINEN_DHT22_PINNI = 4
VARASTO_POHJOINEN_DHT22_LUKUVALI = 60
VARASTO_POHJOINEN_RELE1_PINNI = 6 #29
VARASTO_POHJOINEN_RELE2_PINNI = 5 #31
VARASTO_POHJOINEN_RELE3_PINNI = 19
VARASTO_POHJOINEN_RELE4_PINNI = 26
VARASTO_POHJOINEN_RELE1_MQTTAIHE_1 = 'koti/ulko/etela/valaistusautokatos'  # aihe josta valon status luetaan
VARASTO_POHJOINEN_RELE2_MQTTAIHE_2 = 'koti/ulko/pohjoinen/valaistusterassi'
VARASTO_POHJOINEN_RELE3_MQTTAIHE_3 = 'vara'  # varalla
VARASTO_POHJOINEN_RELE4_MQTTAIHE_4 = 'vara'  # varalla
LIIKETUNNISTIN_ETELA_1 = 'koti/ulko/etela/pir1'
LIIKE_PAALLAPITO_AIKA = 20
LONGITUDI = 22.937540
LATITUDI = 59.836250
VALO_ENNAKKO_AIKA = "06:30"
VALO_ENNAKKO_PAALLE = 30
VALOT_POIS_KLO = "22:00"
